#+title: My Emacs configuration

This repository contains my personal Emacs configuration.

* Technical choices

- no literate configuration
- =use-package.el=[fn:1] along with =straight.el=[fn:2] for package management
- =consult=, =embark=, =marginalia= and =embark= [fn:3] for completion
- respects the Emacs reserved keys[fn:4] for the user as much as possible
- single /huge/ init file
- hooks defined preferably in the most commons/general packages

* Installation

This repo can be cloned and used as it is. Either clone and =make=, or clone and
simply launch Emacs.

Please note that I use a git sub module for my private variables and config.
They are auto-loaded by this config if available, and not mandatory.

* A bit of history

After 3 or 4 Emacs bankruptcy[fn:5] over the course of 8 or so years, I have
decided to reset my git once more today [2020-12-13 Sun]. Not because I've
rewritten it again, but because it has been stable for almost 2 years, and it is
time for it to being clean from any personal and sensitive variables, and can
therefore be publicly shared.

I went through many configuration paradigms, in the following order:
- A copy and paste snippets 'chaos' configuration,
- A literate configuration,
- A literate configuration with =use-package=[fn:1],
- A literate, Spacemacs[fn:6] inspired, configuration with =use-package=, =evil=,
  =which-key=, =leader-key=, etc...
- A plain vanilla config, heavily inspired by Oremacs[fn:7], by Oleh Krehel,
  (Abo-Abo), and Ambrevar's configuration[fn:8], using the built-in =package.el=,
  with =evil= bindings, and then back to classic bindings,
- A =use-package= + =straight=[fn:2] configuration, centered on a single init file.
- A completion engine revolving arround =helm=, and then =ivy=.

And every combination in-between which are not worth mentioning as they were
either small iterations, or short lived.

[2022-05-03 Tue]
In the previous weeks/months, the following changes happened:
- from =ivy= to consult[fn:3] and its other related packages,
- from =eglot=[fn:9] to =lsp=[fn:10]

* Footnotes

[fn:1] https://github.com/jwiegley/use-package

[fn:2] https://github.com/raxod502/straight.el

[fn:3] https://github.com/minad/consult

[fn:4] https://www.masteringemacs.org/article/mastering-key-bindings-emacs

[fn:5] https://www.emacswiki.org/emacs/DotEmacsBankruptcy

[fn:6] https://www.spacemacs.org/

[fn:7] https://github.com/abo-abo/oremacs

[fn:8] https://gitlab.com/ambrevar/dotfiles

[fn:9] https://github.com/joaotavora/eglot

[fn:10]https://emacs-lsp.github.io/lsp-mode/
